#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#export PATH=$HOME/.nodebrew/current/bin:$PATH
export PATH=/usr/local/Cellar/coreutils/8.29/libexec/gnubin/:$PATH
# export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH
export PATH=/Users/onozawa_yushi/Library/Android/sdk/platform-tools:$PATH

autoload colors
colors

HISTFILE="$HOME/.zsh_history"

HISTSIZE=100000
SAVEHIST=100000

setopt share_history
setopt hist_ignore_space

case "${TERM}" in
kterm*|xterm)
    precmd() {
        echo -ne "\033]0;${USER}@${HOST}\007"
    }
    ;;
esac 

fpath=(~/.functions ${fpath})
autoload -Uz git-escape-magic
git-escape-magic

autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^P" history-beginning-search-backward-end
bindkey "^N" history-beginning-search-forward-end 

export LSCOLORS=gxfxxxxxcxxxxxxxxxgxgx
export LS_COLORS='di=01;36:ln=01;35:ex=01;32'
zstyle ':completion:*' list-colors 'di=36' 'ln=35' 'ex=32'

autoload -Uz zmv
alias zmv='noglob zmv -W'
alias cleancheck='git clean -xdf -e .idea && npm cache clean --force && npm install'

fpath=(~/.zsh/completion $fpath)

autoload -U compinit
compinit -u
